### PR TITLE
[EPGImport.py] use the real path epg.dat not simlink

### PR DESCRIPTION
**Pull request by Dima73**

### CODE REVIEW

**Comment by milosoftware** [comment]
That won't really work, it will read the config at startup, so if you change the value, the plugin wouldn't find out.

**Comment by Dima73** [comment]
Milo
I know about it.
Location epg.dat change very rarely.
But...
But as it is now does not work (/hdd/epg.dat).

Although be replaced by /media/hdd/epg.dat

**Comment by eriksl** [comment]
I think it's useful.

Applied.

**Comment by Dima73** [comment]
eriksl no, no
please return the patch, it is no longer needed

**Comment by eriksl** [comment]
I don't have a symlink /hdd/epg.dat to the proper egd.dat file (somewhere else), so for me it makes sense. How can this break things?

**Comment by Dima73** [comment]
Milo, have corrected it.
https://github.com/OpenPLi/enigma2-plugin-extensions-xmltvimport/commit/a2cf00f0f6d9e5f8a3106ce99733aafe0e699993

**Comment by eriksl** [comment]
Hmmm, MiLo is on a different track here. I guess config isn't available when running outside enigma.

Reverted.

**Pull request closed without merging**
